
// This file was auto-generated by ML.NET Model Builder. 

using AnimalsAutoML_ConsoleApp1;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\uabor\Downloads\animals_dataset\animals_dataset\train\cat\download (1).jpeg");
AnimalsAutoML.ModelInput sampleData = new AnimalsAutoML.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var sortedScoresWithLabel = AnimalsAutoML.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}
